config/routes.rb
Fabsoft::Application.routes.draw do
  resources :courses do
    collection do
      put 'current_courses' => 'courses#register', as: :register
      get "registered_students/:id" => 'courses#registered_students', as: :registered_students
    end
  end

  resources :projects
  resources :partners
  resources :abouts
  resources :members
  resources :students
  devise_for :users

  get "welcome/index"
  get "welcome/about"
  get "welcome/partners"
  get "welcome/projects"
  get "welcome/members"
  get "welcome/current_courses"
  get "welcome/see_more/:id" => 'welcome#see_more', as: :see_more
  

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @projects = projects.first(3)
  end

  def about
  	@about = About.first
  end

  def partners
  	@partners = Partner.all
  end

  def projects
    @projects = Project.all
  end

  def members
    @control = true
  	@members = Member.all
  end

  def courses
    @courses = courses.all
  end

  def see_more
    @course = Course.find(params[:id])
  end

  def current_courses
    @courses = Course.all
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="jumbotron">
  <h1><%= @about.title %></h1><br>
  <p><%= raw(@about.content) %></p>
</div>

app/views/welcome/current_courses.html.erb
<div class="page-header">
    <h1>Listing courses</h1>
  </div>
<div class="container marketing">
  <div class="row">
    <% @courses.each do |course| %>
      <a href="<%= see_more_path(course) %>" class="mudaTexto mudaCorIcones">
        <div class="col-xs-4 text-center">
          <div class="panel panel-default">
            <div class="panel-body">
              <h2><span class="mudaTexto"><%= course.name %></span></h2>
              <%= image_tag course.image_url(:thumb).to_s, :size => '200x200' %>
              <h4><i class="glyphicon glyphicon-time"></i> <%= course.workload %> horas </h4>
              <% if current_user.present? && current_user.role?('estudante') %> 
                <%= link_to "Inscrever-se", register_courses_path(:id => course.id),:method => :put, :role => "button", :class => "btn btn-success btn-md btn-block" %>
              <% end %>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div> <!-- row -->
</div> <!-- marketing -->



<!-- Parte da POG que não é visivel
  <% if false %>
  <%= link_to 'Show', course, :class => "btn btn-primary", :role => "button" %>
  <%= link_to 'Edit', edit_course_path(course), :class => "btn btn-primary", :role => "button" %>
  <%= link_to 'Destroy', course, :class => "btn btn-primary", :role => "button", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
-->

app/views/welcome/index.html.erb
<style type="text/css">
body {
	padding-top: 51px;
}
</style>

<div class="container">
    <div class="row" style="padding-top: -10px">
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
			    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
			  	<div class="item active">
			      <img src="/assets/c1.jpg" alt="...">
			      <div class="carousel-caption">
			      </div>
			    </div>

			    <div class="item">
			      <img src="/assets/c2.jpg" alt="..." width="1170px">
			      <div class="carousel-caption">
			      </div>
			    </div>

			    <div class="item">
			      <img src="/assets/c3.jpg" alt="...">
			      <div class="carousel-caption">
			      </div>
			    </div>

			    <div class="item">
			      <img src="/assets/c4.jpg" alt="...">
			      <div class="carousel-caption">
			      </div>
			    </div>

			    <div class="item">
			      <img src="/assets/c5.jpg" alt="...">
			      <div class="carousel-caption">
			      </div>
			    </div>
			  </div>

			  <!-- Controls -->
			  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left"></span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right"></span>
			  </a>
			</div>
	</div>
</div> <br>

<!-- radio: 2,325439 -->
<div class="page-header">
	<h1>Projects</h1>
</div>
<div class="container marketing">
 <!-- Three columns of text below the carousel -->
      <div class="row">
      	<% @projects.each do |project| %>
	        <div class="col-md-4 text-center">
    			<h2 style="margin-center: 120px;"><span class="text-muted"><%= project.name %></span></h2>
	          	<p><%= raw(project.description) %></p>
	        </div><!-- /.col-lg-4 -->
        <% end %>
      </div><!-- /.row -->
</div>

app/views/welcome/members.html.erb
<div class="page-header">
	<h2>Membros</h2>
</div>

<% @members.each do |member| %>
	<% if @control %>
	<div class="row featurette">
	   <div class="col-md-9">
		    <h2 class="featurette-heading"><%= member.name %></h2><br>
		    <p class="lead">E-mail:<span class="text-muted"> <%= member.email %></span></p>
		    <p class="lead">Telephone:<span class="text-muted"> <%= member.cellphone %></span></p>

		 	<a href="<%= member.twitter %>" target="_blank"><%= image_tag('twitter-bird.png', class: "social-slide") if member.twitter!="" %></a>
		 	<a href="<%= member.gplus %>" target="_blank"><%= image_tag('gplus.jpg', class: "social-slide") if member.gplus!="" %></a>
		 	<a href="<%= member.facebook %>" target="_blank"><%= image_tag('facebook.png', class: "social-slide") if member.facebook!="" %></a>
		 	<a href="<%= member.github %>" target="_blank"><%= image_tag('github.png', class: "social-slide") if member.github!="" %></a>
		 	<a href="<%= member.linkedin %>" target="_blank"><%= image_tag('linkedin.png', class: "social-slide") if member.linkedin!="" %></a>
	   </div>
	   <div class="col-md-3">
	     <%= image_tag member.image_url(:thumb).to_s, class: "img-thumbnail" %>
	   </div>
	   <% @control = false %>
	</div>
	<hr>
	<% else %>		
	 <div class="row featurette">
	    <div class="col-md-7">
	      <%= image_tag member.image_url(:thumb).to_s, class: "img-thumbnail" %>
	    </div>
	    <div class="col-md-5">
	 	    <h2 class="featurette-heading"><%= member.name %></h2><br>
	 	    <p class="lead">E-mail:<span class="text-muted"> <%= member.email %></span></p>
	 	    <p class="lead">Telephone:<span class="text-muted"> <%= member.cellphone %></span></p>

	 	 	<a href="<%= member.twitter %>" target="_blank"><%= image_tag('twitter-bird.png', class: "social-slide") if member.twitter!="" %></a>
	 	 	<a href="<%= member.gplus %>" target="_blank"><%= image_tag('gplus.jpg', class: "social-slide") if member.gplus!="" %></a>
	 	 	<a href="<%= member.facebook %>" target="_blank"><%= image_tag('facebook.png', class: "social-slide") if member.facebook!="" %></a>
	 	 	<a href="<%= member.github %>" target="_blank"><%= image_tag('github.png', class: "social-slide") if member.github!="" %></a>
	 	 	<a href="<%= member.linkedin %>" target="_blank"><%= image_tag('linkedin.png', class: "social-slide") if member.linkedin!="" %></a>
	    </div>
	  </div>
	  <% @control = true %>
	  <hr>
	<% end %>
<% end %>


<style type="text/css">
.social-slide {
	background-image: url('/assets/twitter-bird');
	height: 48px;
	width: 48px;
	margin: 10px;
	float: left;
	-webkit-transition: all ease 0.3s;
	-moz-transition: all ease 0.3s;
	-o-transition: all ease 0.3s;
	-ms-transition: all ease 0.3s;
	transition: all ease 0.3s;
	cursor: pointer
}

.social-slide:hover {
	background-position: 0px -48px;
	box-shadow: 0px 0px 4px 1px rgba(0,0,0,0.8);
}
</style>

<script type="text/javascript">
	
</script>

app/views/welcome/partners.html.erb
<div class="page-header">
  <h2>Partners</h2>
</div>

<div class="row">
  <% @partners.each do |partner| %>
    <div class="col-md-12">
      <center>
        <%= image_tag partner.image, alt: "Generic placeholder image", class: "img-rounded" %>
      </center>
      <p class="lead"><span class="text-muted"> <%= raw(partner.description) %></span></p>
      <p><%= link_to "WebSite!", partner.url, class: "btn btn-primary" %></p>
      <hr>
   </div>
  <%end %>
</div>

app/views/welcome/projects.html.erb
<div class="page-header">
  <h2>Projects</h2>
</div>

<div class="row featurette">
  <% @projects.each do |project| %>
   <div class="col-md-12">
      <center>
        <%= image_tag project.image, alt: "Generic placeholder image", class: "img-rounded" %>
      </center>
      <p class="lead"><span class="text-muted"> <%= raw(project.description) %></span></p>
      <p><%= link_to "WebSite!", project.url, class: "btn btn-primary" %></p>
      <hr>
   </div>
   <% end %>
 </div> <!-- end row -->

app/views/welcome/see_more.html.erb
<div class="container">
	<div class="row clearfix">
		<div class="col-md-8 column">
			<div>
				<div id="quadroCursosUsers">
					<h1><%= @course.name %> </h1>
				</div>
				<br/>	
				<p align="center">
					<%= image_tag @course.image_url(:thumb).to_s, :size => '250x350', class: "img-responsive" %>
				</p>
				<br/>
				<strong>Specification:</strong>
				<div class="pogPular" type="text">
					<p> <%= raw(@course.specification) %></p>
				</div>
				<%= link_to 'Back', welcome_current_courses_path, class: "btn btn-primary" %>
			</div>
		</div>
		
		<div class="col-md-4 column well">
			<div id="espacosParaAmbosOsLados">
				<h3 id="margemParabaixo">Informations</h3>
				<h4><i class="glyphicon glyphicon-time"></i><strong> Workload:</strong> <%= @course.workload %> </h4>
				<h4><i class="glyphicon glyphicon-calendar"></i><strong> Start date:</strong> <%= @course.start_date %> </h4>
				<h4><i class="glyphicon glyphicon-calendar"></i><strong> End date:</strong> <%= @course.end_date %> </h4>
				<h4><i class="glyphicon glyphicon-plus"></i><strong> Maximum capacity:</strong> <%= @course.maximum_capacity %> </h4>
				<h4 id="margemParabaixo"><i class="glyphicon glyphicon-minus"></i><strong> Minimum capacity:</strong> <%= @course.minimum_capacity %> </h4>
				<hr/>
				<h3 id="margemParabaixo">Instructors</h3>
			</div>
			
			<% @course.users.each do |u| %>
			<div class="col-md-6" align="center" >
				<%= image_tag u.image_url(:thumb).to_s, size: "100x100", class: "img-circle " if u.type == "Member" %>
				<br/>
				<br/>
				<strong ><%= u.name if u.type == "Member" %></strong>
				<br/>
				<br/>
			</div>
			<% end %>
			<br/>
		</div>
	</div>
</div>