config/routes.rb
Fabsoft::Application.routes.draw do
  resources :courses do
    collection do
      put 'current_courses' => 'courses#register', as: :register
      get "registered_students/:id" => 'courses#registered_students', as: :registered_students
    end
  end

  resources :projects
  resources :partners
  resources :abouts
  resources :members
  resources :students
  devise_for :users

  get "welcome/index"
  get "welcome/about"
  get "welcome/partners"
  get "welcome/projects"
  get "welcome/members"
  get "welcome/current_courses"
  get "welcome/see_more/:id" => 'welcome#see_more', as: :see_more
  

  root 'welcome#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :registered_students]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    add_breadcrumb "List Courses", courses_path
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    add_breadcrumb "List Courses", courses_path
    add_breadcrumb "Show Course", course_path(@course)
  end

  # GET /courses/new
  def new
    @members = Member.includes(:roles).where("roles.name = 'membro'")
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    @members = Member.includes(:roles).where("roles.name = 'membro'")
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def register
    @course = Course.find(params[:id])
    if current_user.present? && current_user.role?("estudante") 
      @course.users << current_user
      @course.update_attributes(users: @course.users)
      redirect_to root_path, notice: "Course was successfully updated."
    else
      redirect_to root_path, alert: "Course wasn't successfully updated."
    end
  end


  def registered_students
    # Recover from db, students that had been registered in that course.
    add_breadcrumb "List Courses", courses_path
    add_breadcrumb "List Students", registered_students_courses_path(@course)
    @students = User.includes(:courses).where("courses.id = '#{@course.id}' && type = 'Student'")
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def current_courses
    @courses = Course.all
    add_breadcrumb "List Courses", courses_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :workload, :specification, :start_date, :end_date, :maximum_capacity, :minimum_capacity, :image, :url,:user_ids => [])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Course</h3>
      </div>
      <br>
        <div class="panel-body">
          <%= simple_form_for @course, :html => { :class => 'form-horizontal' }  do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">

            <div class="form-group">
              <div class="col-xs-4">
                <%= f.input :name %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-4">
                <%= f.input :workload %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-12">
                <%= f.input :specification %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-4">
                <%= f.input :start_date, :as => :string, :input_html => { data: {behaviour: "datepicker"}} %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-4">
                <%= f.input :end_date, :as => :string, :input_html => { data: {behaviour: "datepicker"}} %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-4">
                <%= f.input :maximum_capacity %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-4">
                <%= f.input :minimum_capacity %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-4">
                <%= f.input :image %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-3">
                <%= f.association :users, collection: @members, as: :check_boxes %>
              </div>
            </div>            
            
          </div>

          <div class="well">
            <%= f.button :submit, class: "btn btn-primary" %>
            <%= link_to 'Back', courses_path, class: "btn btn-default" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $('[data-behaviour~=datepicker]').datepicker({
      "format": "yyyy-mm-dd",
      "weekStart": 1,
      "autoclose": true
    });
  </script>

app/views/courses/alunos_cadastrados.html.erb
<div class="page-header">
  <h1>Listing members</h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Members</h3>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          
          <th>Type</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
            <td><%= student.type %></td>
            
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- End Panel -->
</div>
<br>

<%= link_to 'New Member', new_member_path %>

app/views/courses/current_courses.html.erb
<div class="page-header">
    <h1>Listing courses</h1>
  </div>
<div class="container marketing">
  <div class="row">
    <% @courses.each do |course| %>
      <a href="<%= see_more_path(course) %>" class="mudaTexto mudaCorIcones">
        <div class="col-xs-4 text-center">
          <div class="panel panel-default">
            <div class="panel-body">
              <h2><span class="mudaTexto"><%= course.name %></span></h2>
              <%= image_tag course.image_url(:thumb).to_s, :size => '200x200' %>
              <h4><i class="glyphicon glyphicon-time"></i> <%= course.workload %> horas </h4> 
              <%= link_to "Inscrever-se", inscrever_se_courses_path(:id => course.id),:method => :put, :role => "button", :class => "btn btn-success btn-md btn-block" %>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div> <!-- row -->
</div> <!-- marketing -->



<!-- Parte do código que não é visivel -->
  <% if false %>
  <%= link_to 'Show', course, :class => "btn btn-primary", :role => "button" %>
  <%= link_to 'Edit', edit_course_path(course), :class => "btn btn-primary", :role => "button" %>
  <%= link_to 'Destroy', course, :class => "btn btn-primary", :role => "button", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="container" >
  <div class="row">
    <div class="col-md-12">
      <% @courses.each do |course| %>
      <div class="col-md-4 text-center">
        <div class="col-md-12">
          <h3 class="mudaTexto text-center"><%= course.name %></h3><br/>
        </div>
        <br/>
        <%= image_tag course.image_url(:thumb).to_s, :size => '200x200', class: "img-rounded" %><br/>
        <strong>Workload</strong> <%= course.workload %><br/>
        <strong>Start date</strong> <%= course.start_date %><br/>
        <strong>End date</strong> <%= course.end_date %><br/>
        <strong>Maximum capacity</strong> <%= course.maximum_capacity %><br/>
        <strong>Minimum capacity</strong> <%= course.minimum_capacity %>
        <br/>
        <br/>
        <div class="col-md-12 text-center">
          <%= link_to 'Show', course, class: "btn btn-info" %>
          <%= link_to 'Edit', edit_course_path(course), class: "btn btn-primary" %>
          <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <%= link_to 'Ver Alunos', registered_students_courses_path(course), class: "btn btn-success" %>
        </div>
        <br/>
        <br/>
        <br/>
      </div>    
      <% end %>  
    </div>    
  </div>
</div>
<br/>
<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/registered_students.html.erb
<div class="page-header">
  <h1>Listing Registered Students</h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Members</h3>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Type</th>
        </tr>
      </thead>

      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.name %></td>
            <td><%= student.email %></td>
            <td><%= student.type %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- End Panel -->
</div>
<br>

app/views/courses/show.html.erb
<div class="container">
  <div class="row clearfix">


    <div class="col-md-8 column">
      <div >
        <div id="quadroCursosUsers">
          <h1><%= @course.name %> </h1>
        </div>

        <br/> 

        <p align="center">
          <%= image_tag @course.image_url(:thumb).to_s, :size => '250x350', class: "img-responsive" %>
        </p>

        <br/>
        <strong>Specification:</strong>
        <div class="pogPular" type="text">
          <p> <%= raw(@course.specification) %></p>
        </div>

        <%= link_to 'Edit', edit_course_path(@course), class: "btn btn-primary" %> 
        <%= link_to 'Back', courses_path, class: "btn btn-primary" %>
      </div>
    </div>
    
    <div class="col-md-4 column well">
      <div id="espacosParaAmbosOsLados">
        <h3 id="margemParabaixo">Informations</h3>
        <h4><i class="glyphicon glyphicon-time"></i><strong> Workload:</strong> <%= @course.workload %> </h4>
        <h4><i class="glyphicon glyphicon-calendar"></i><strong> Start date:</strong> <%= @course.start_date %> </h4>
        <h4><i class="glyphicon glyphicon-calendar"></i><strong> End date:</strong> <%= @course.end_date %> </h4>
        <h4><i class="glyphicon glyphicon-plus"></i><strong> Maximum capacity:</strong> <%= @course.maximum_capacity %> </h4>
        <h4 id="margemParabaixo"><i class="glyphicon glyphicon-minus"></i><strong> Minimum capacity:</strong> <%= @course.minimum_capacity %> </h4>
        <hr/>

        <h3 id="margemParabaixo">Instructors</h3>

      </div>
      
      <% @course.users.each do |u| %>
      <div class="col-md-6" align="center" >
        <%= image_tag u.image_url(:thumb).to_s, size: "100x100", class: "img-circle " if u.type == "Member" %>
        <br/>
        <br/>
        <strong ><%= u.name if u.type == "Member" %></strong>
        <br/>
        <br/>
      </div>
      <% end %>
      <br/>
      
    </div>

  </div>
</div>