config/routes.rb
Fabsoft::Application.routes.draw do
  resources :courses do
    collection do
      put 'current_courses' => 'courses#register', as: :register
      get "registered_students/:id" => 'courses#registered_students', as: :registered_students
    end
  end

  resources :projects
  resources :partners
  resources :abouts
  resources :members
  resources :students
  devise_for :users

  get "welcome/index"
  get "welcome/about"
  get "welcome/partners"
  get "welcome/projects"
  get "welcome/members"
  get "welcome/current_courses"
  get "welcome/see_more/:id" => 'welcome#see_more', as: :see_more
  

  root 'welcome#index'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
	<div class="container">
	  	<!-- Brand and toggle get grouped for better mobile display -->
	  	<div class="navbar-header">
		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		      	<span class="sr-only">Toggle navigation</span>
		      	<span class="icon-bar"></span>
		      	<span class="icon-bar"></span>
		      	<span class="icon-bar"></span>
		    </button>
		    <a class="brand" href="/"><%= image_tag 'Fabsoft-logo-mini.png', size: "120x30", style: "margin: 7px;" %></a>
	  	</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    <ul class="nav navbar-nav">
	    		<li><a href="/welcome/partners"><span class="glyphicon glyphicon-briefcase"> Partners</span></a></li>
		    	<li><a href="/welcome/projects"><span class="glyphicon glyphicon-folder-open"> Projects</span></a></li>
		    	<li><a href="/welcome/members"><span class="glyphicon glyphicon-user"> Members</span></a></li>
	    		<li><a href="/welcome/current_courses"><span class="glyphicon glyphicon-book"> Courses</span></a></li>

		    	<% if current_user.present? && current_user.role?('admin') %>
		    		<li class="dropdown">
	    	        	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-wrench"></span><b class="caret"></b></a> 
		    	        <ul class="dropdown-menu">
		    	           	<li><%= link_to "Members", members_path %></li>
		    	           	<li><%= link_to "Students", students_path %></li>
		    	           	<li><%= link_to "About", abouts_path %></li>
		    	           	<li><%= link_to "Partners", partners_path %></li>
		    	           	<li><%= link_to "Projects", projects_path %></li>
		    	           	<li><%= link_to "Courses", courses_path %></li>

		    	        </ul>
	    	    	</li>
	    	    <% end %>
		    </ul>
		    
		    <ul class="nav navbar-nav navbar-right">
              <% if !user_signed_in? %>
                      <li><%= link_to " Login", "#myModal", data: {toggle: "modal"}, class: "glyphicon glyphicon-log-in" %></li>
              <% else %>
                      <li><%= link_to " "+current_user.name.to_s.split(" ").first.capitalize, edit_user_registration_path(current_user), class: "glyphicon glyphicon-user" %></li>
                      <li><%= link_to " Logout", destroy_user_session_path, method: 'delete', class: 'glyphicon glyphicon-log-out' %></li>
              <% end %>
            </ul>
	  	</div><!-- /.navbar-collapse -->
	</div>
</nav>

<!-- Modal Login -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        		<h4 class="modal-title" id="myModalLabel"><span class="label label-success">Login</span></h4>
      		</div>
      		<%= simple_form_for(:user, :url => session_path(:user)) do |f| %>
  				<div class="modal-body">
      				<div class="form-inputs">
    					<%= f.input :login, :required => false, :autofocus => true, label: "Username:" %>
        				<%= f.input :password, :required => false %>
      				</div>
					</div>
  				<div class="modal-footer">
    				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    				<%= f.button :submit, "Sign in", class: "btn btn-primary" %>
  				</div>
  			<% end %>
    	</div>
  	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FabSoft</title>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-5439110-2', '107.170.24.19');
	  ga('send', 'pageview');

	</script>
</head>
<body>
	<div class="container responsive">
		<div class="row">
			<%= render 'layouts/navbar' %>
			<%= render 'layouts/messages' %>
			<% if params[:controller] != 'welcome' && params[:controller] != 'devise/registrations' && params[:controller] != 'devise/sessions' %>
				<ol class="breadcrumb">
					<%= render_breadcrumbs :tag => :li, :separator => "" %>
				</ol>
			<% end %>  
			<%= yield %>
		</div>
		<hr>
		<div class="panel-footer">
			<div class="pull-right">
				<a href="https://twitter.com/fabsoftcesupa" target="_blank"><%= image_tag('twitter-bird.png', size: "40x40", class: "social-slide2") %></a>
				<a href="https://www.facebook.com/Fabsoft" target="_blank"><%= image_tag('facebook.png', size: "40x40", class: "social-slide2") %></a>
			</div>
			<p>&copy; <%= Time.now.year %> FabSoft - Fabrica de Software do CESUPA. All rights reserved.</p>
			<p>Av. Governador José Malcher, 1963</p>
			<p>Cep: 66.060-230</p>
			<p>Fone: (91) 4009 - 9179</p>
			<p>Belém - PA - Brasil</p>
       </div>
	</div>
</body>
</html>

<style type="text/css">
.social-slide2 {
	background-image: url('/assets/twitter-bird');
	-webkit-transition: all ease 0.3s;
	-moz-transition: all ease 0.3s;
	-o-transition: all ease 0.3s;
	-ms-transition: all ease 0.3s;
	transition: all ease 0.3s;
	cursor: pointer
}

.social-slide2:hover {
	background-position: 0px -48px;
	box-shadow: 0px 0px 4px 1px rgba(0,0,0,0.8);
}
</style>